ESSIFI-102: added dockerfile and docker-compose file
Sphereon-Opensource/pe-ms pull request #3
Opened 2021-08-23 13:30 UTC by sksadjad

added Dockerfile & docker-compose for generating image and publishing it

2021-08-25 07:21 UTC, maikel-maas commented on Dockerfile
> +RUN npm start ./index.ts
The start script uses nodemon which is development mode. We need to transpile it first and then run it from the build folder.

2021-08-25 07:23 UTC, maikel-maas commented on Dockerfile
> +COPY sphereon-pe-models-*.tgz ./
I think we can even remove this and pull it from npm remote repository

2021-08-25 07:39 UTC, maikel-maas requested changes
Almost there! :-)

2021-08-25 09:45 UTC, hrehman-sphereon commented
We should be using PE-JS as dependency not PE-Models.
We should rename the project to pe-ms
The packages.json should have the name @sphereon/pe-ms
version 0.0.1
"license": "Apache-2.0",

Add unit tests
Add documentation to build , test , run seperately & run in docker.

remove hard coded token

2021-08-25 09:45 UTC, hrehman-sphereon requested changes
comments added already: Please have a look

2021-11-15 09:20 UTC, hrehman-sphereon requested changes
There are some dependency related and README related comments

2021-11-15 09:20 UTC, hrehman-sphereon commented on README.md
> +You can simply start the service with running `docker-compose up` at the root of project
We should add more details about how to see it running. For example we need to add a link to swagger/postman workspace where we should have the ready examples to send request and see responses.

2021-11-15 09:20 UTC, hrehman-sphereon commented on README.md
> +nodemon src/index.ts
I got this error on the first run: 'ts-node' is not recognized as an internal or external command, operable program or batch file.
We should add such dependencies command already in the README.

2021-11-15 10:04 UTC, merged